name: core_common
description: Common utilities and result types for Transcripto
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
