name: domain
description: Domain layer with entities, repositories and use cases for Transcripto
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  core_common:
    path: ../core_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
