name: core_common
description: Shared common utils and result types for Transcripto.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.0
