name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
        working-directory: android_flutter/transcripto
      - name: Analyze
        run: flutter analyze
        working-directory: android_flutter/transcripto
      - name: Test
        run: flutter test --coverage
        working-directory: android_flutter/transcripto
      - name: Build APK
        run: flutter build apk --release
        working-directory: android_flutter/transcripto
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: transcripto-apk
          path: android_flutter/transcripto/build/app/outputs/flutter-apk/app-release.apk
