# SwiftLint Configuration for Transcripto
# Archivo de configuración para SwiftLint

# Archivos y carpetas a incluir en el análisis
included:
  - transcripto_calude

# Archivos y carpetas a excluir del análisis
excluded:
  - transcripto_calude.xcodeproj
  - scripts
  - .git

# Configuración del analizador
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

# Reglas habilitadas
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Reglas deshabilitadas
disabled_rules:
  - todo # Permitir comentarios TODO durante desarrollo
  - line_length # Será manejado por SwiftFormat

# Configuración de reglas específicas
file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 350

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

force_cast:
  severity: error

force_try:
  severity: error

# Configuración de archivo de encabezado
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  transcripto_calude
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/

# Configuración de importaciones
sorted_imports:
  severity: warning

# Configuración para métodos de prueba
single_test_class:
  test_parent_classes:
    - XCTestCase
    - CipherTestCase
